// Generated by gencpp from file cozmo_rc/light_reqRequest.msg
// DO NOT EDIT!


#ifndef COZMO_RC_MESSAGE_LIGHT_REQREQUEST_H
#define COZMO_RC_MESSAGE_LIGHT_REQREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cozmo_rc
{
template <class ContainerAllocator>
struct light_reqRequest_
{
  typedef light_reqRequest_<ContainerAllocator> Type;

  light_reqRequest_()
    : red(false)
    , blue(false)
    , green(false)
    , white(false)  {
    }
  light_reqRequest_(const ContainerAllocator& _alloc)
    : red(false)
    , blue(false)
    , green(false)
    , white(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _blue_type;
  _blue_type blue;

   typedef uint8_t _green_type;
  _green_type green;

   typedef uint8_t _white_type;
  _white_type white;





  typedef boost::shared_ptr< ::cozmo_rc::light_reqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cozmo_rc::light_reqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct light_reqRequest_

typedef ::cozmo_rc::light_reqRequest_<std::allocator<void> > light_reqRequest;

typedef boost::shared_ptr< ::cozmo_rc::light_reqRequest > light_reqRequestPtr;
typedef boost::shared_ptr< ::cozmo_rc::light_reqRequest const> light_reqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cozmo_rc::light_reqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cozmo_rc::light_reqRequest_<ContainerAllocator1> & lhs, const ::cozmo_rc::light_reqRequest_<ContainerAllocator2> & rhs)
{
  return lhs.red == rhs.red &&
    lhs.blue == rhs.blue &&
    lhs.green == rhs.green &&
    lhs.white == rhs.white;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cozmo_rc::light_reqRequest_<ContainerAllocator1> & lhs, const ::cozmo_rc::light_reqRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cozmo_rc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::light_reqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::light_reqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::light_reqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31d336e006298e5af6b1db3920570f3b";
  }

  static const char* value(const ::cozmo_rc::light_reqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31d336e006298e5aULL;
  static const uint64_t static_value2 = 0xf6b1db3920570f3bULL;
};

template<class ContainerAllocator>
struct DataType< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cozmo_rc/light_reqRequest";
  }

  static const char* value(const ::cozmo_rc::light_reqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool red\n"
"bool blue\n"
"bool green\n"
"bool white\n"
;
  }

  static const char* value(const ::cozmo_rc::light_reqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.blue);
      stream.next(m.green);
      stream.next(m.white);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct light_reqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cozmo_rc::light_reqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cozmo_rc::light_reqRequest_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
    s << indent << "green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green);
    s << indent << "white: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.white);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COZMO_RC_MESSAGE_LIGHT_REQREQUEST_H
