// Generated by gencpp from file cozmo_rc/light_reqResponse.msg
// DO NOT EDIT!


#ifndef COZMO_RC_MESSAGE_LIGHT_REQRESPONSE_H
#define COZMO_RC_MESSAGE_LIGHT_REQRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cozmo_rc
{
template <class ContainerAllocator>
struct light_reqResponse_
{
  typedef light_reqResponse_<ContainerAllocator> Type;

  light_reqResponse_()
    {
    }
  light_reqResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cozmo_rc::light_reqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cozmo_rc::light_reqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct light_reqResponse_

typedef ::cozmo_rc::light_reqResponse_<std::allocator<void> > light_reqResponse;

typedef boost::shared_ptr< ::cozmo_rc::light_reqResponse > light_reqResponsePtr;
typedef boost::shared_ptr< ::cozmo_rc::light_reqResponse const> light_reqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cozmo_rc::light_reqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cozmo_rc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::light_reqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::light_reqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::light_reqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cozmo_rc::light_reqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cozmo_rc/light_reqResponse";
  }

  static const char* value(const ::cozmo_rc::light_reqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::cozmo_rc::light_reqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct light_reqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cozmo_rc::light_reqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cozmo_rc::light_reqResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COZMO_RC_MESSAGE_LIGHT_REQRESPONSE_H
