// Generated by gencpp from file cozmo_rc/speaker_reqRequest.msg
// DO NOT EDIT!


#ifndef COZMO_RC_MESSAGE_SPEAKER_REQREQUEST_H
#define COZMO_RC_MESSAGE_SPEAKER_REQREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cozmo_rc
{
template <class ContainerAllocator>
struct speaker_reqRequest_
{
  typedef speaker_reqRequest_<ContainerAllocator> Type;

  speaker_reqRequest_()
    : data()  {
    }
  speaker_reqRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> const> ConstPtr;

}; // struct speaker_reqRequest_

typedef ::cozmo_rc::speaker_reqRequest_<std::allocator<void> > speaker_reqRequest;

typedef boost::shared_ptr< ::cozmo_rc::speaker_reqRequest > speaker_reqRequestPtr;
typedef boost::shared_ptr< ::cozmo_rc::speaker_reqRequest const> speaker_reqRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator1> & lhs, const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator1> & lhs, const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cozmo_rc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992ce8a1687cec8cULL;
  static const uint64_t static_value2 = 0x8bd883ec73ca41d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cozmo_rc/speaker_reqRequest";
  }

  static const char* value(const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
;
  }

  static const char* value(const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speaker_reqRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cozmo_rc::speaker_reqRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cozmo_rc::speaker_reqRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COZMO_RC_MESSAGE_SPEAKER_REQREQUEST_H
