// Generated by gencpp from file cozmo_rc/speaker_req.msg
// DO NOT EDIT!


#ifndef COZMO_RC_MESSAGE_SPEAKER_REQ_H
#define COZMO_RC_MESSAGE_SPEAKER_REQ_H

#include <ros/service_traits.h>


#include <cozmo_rc/speaker_reqRequest.h>
#include <cozmo_rc/speaker_reqResponse.h>


namespace cozmo_rc
{

struct speaker_req
{

typedef speaker_reqRequest Request;
typedef speaker_reqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_req
} // namespace cozmo_rc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cozmo_rc::speaker_req > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::cozmo_rc::speaker_req&) { return value(); }
};

template<>
struct DataType< ::cozmo_rc::speaker_req > {
  static const char* value()
  {
    return "cozmo_rc/speaker_req";
  }

  static const char* value(const ::cozmo_rc::speaker_req&) { return value(); }
};


// service_traits::MD5Sum< ::cozmo_rc::speaker_reqRequest> should match
// service_traits::MD5Sum< ::cozmo_rc::speaker_req >
template<>
struct MD5Sum< ::cozmo_rc::speaker_reqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cozmo_rc::speaker_req >::value();
  }
  static const char* value(const ::cozmo_rc::speaker_reqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cozmo_rc::speaker_reqRequest> should match
// service_traits::DataType< ::cozmo_rc::speaker_req >
template<>
struct DataType< ::cozmo_rc::speaker_reqRequest>
{
  static const char* value()
  {
    return DataType< ::cozmo_rc::speaker_req >::value();
  }
  static const char* value(const ::cozmo_rc::speaker_reqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cozmo_rc::speaker_reqResponse> should match
// service_traits::MD5Sum< ::cozmo_rc::speaker_req >
template<>
struct MD5Sum< ::cozmo_rc::speaker_reqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cozmo_rc::speaker_req >::value();
  }
  static const char* value(const ::cozmo_rc::speaker_reqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cozmo_rc::speaker_reqResponse> should match
// service_traits::DataType< ::cozmo_rc::speaker_req >
template<>
struct DataType< ::cozmo_rc::speaker_reqResponse>
{
  static const char* value()
  {
    return DataType< ::cozmo_rc::speaker_req >::value();
  }
  static const char* value(const ::cozmo_rc::speaker_reqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COZMO_RC_MESSAGE_SPEAKER_REQ_H
